### ISSUE TITLE
full backup needed!

### ISSUE THREAD

**Issue by edmundlaugasson** [belowaverage-org/SuperGrate#60] opened 2021-06-08 13:55 UTC
**Is your feature request related to a problem? Please describe.**
I wanted to create a full backup, but only partial were created :(

**Describe the solution you'd like**
I followed wiki https://wiki.belowaverage.org/software/supersuite/supergrate and the backing up and restore sections. Did as guided, but no email, web browser settings were migrated. This basically means, that only partially %appdata% were migrated.

Would like to see full backup and restore following that guide in mentioned wiki.

I can see these parameters at https://docs.microsoft.com/en-us/windows/deployment/usmt/usmt-reference but quite complex documents, hard to figure out the correct ones....
Found also this one https://docs.microsoft.com/en-us/windows/deployment/usmt/usmt-command-line-syntax

Under SuperGrate settings (F12) are scanstate.exe parameters:
`/config:Config_SettingsOnly.xml /i:MigUser.xml /c /r:3 /o`
and loadstate.exe ones:
`/config:Config_SettingsOnly.xml /i:MigUser.xml /c /r:3 /lac /lae`
It seems, that these are not enough....

**Describe alternatives you've considered**
No alternatives....

**Additional context**
MS Windows 10 version 2004 build 19041.985 were used at this time.

**Comment by krisdb2009** [comment] 2021-06-08 14:47
What version of Super Grate are you on?
I think this may have been fixed in the latest release.

**Comment by edmundlaugasson** [comment] 2021-06-08 15:08
The latest and greatest, just downloaded few hours before I filed the issue here.

**Comment by krisdb2009** [comment] 2021-06-08 15:17
Oh gotcha,

Try doing this:

Once you back up the desired user you want to copy, click "list store" then right click on the user and select "Set destination username..." Enter the new username you want to copy back down as and start restoration.

**Comment by krisdb2009** [comment] 2021-06-08 15:21
This might help too:

https://docs.microsoft.com/en-us/windows/deployment/usmt/usmt-what-does-usmt-migrate

**Comment by edmundlaugasson** [comment] 2021-06-08 15:21
That was the first thing to do! No point to restore to same location... Changing destination username was nicely documented in wiki, I referred. Certainly I wanted to new user profile. Disturbing thing is, that I need to create backup first and then restore it to another location. There could be an option to copy directly, just clone whole profile regardless, what is there.

**Comment by krisdb2009** [comment] 2021-06-08 15:22
There is an option for that, if you fill both the source and destination computer in the migration will happen in one step.

**Comment by edmundlaugasson** [comment] 2021-06-08 15:23
> This might help too:
> 
> https://docs.microsoft.com/en-us/windows/deployment/usmt/usmt-what-does-usmt-migrate

[Looks like not migrating apps settings](https://docs.microsoft.com/en-us/windows/deployment/usmt/usmt-what-does-usmt-migrate#what-usmt-does-not-migrate), also OS settings..... Then it is useless for me.

**Comment by krisdb2009** [comment] 2021-06-08 15:27
Sorry Edmund, not too sure.

USMT does migrate a-lot of stuff, you can customize the xml files in the USMT folder and modify what it copies. By default, the version of USMT Super Grate downloads from this repo has some stuff disabled.

**Comment by edmundlaugasson** [comment] 2021-06-08 15:43
Just wanted a tool to clone the profile, don't have time to dig into XML-world and experiment with those settings, what now with current settings will be migrated and what not. I don't need anything extra - just whole profile clone, that's all.

**Comment by krisdb2009** [comment] 2021-06-08 16:01
Yea, this won't work for this case.
USMT only migrates files and commons settings, that's all.

**Comment by edmundlaugasson** [comment] 2021-06-08 16:05
Then [that advertising on your front page](https://belowaverage.org/software/supersuite/supergrate/)  is misleading:
```
Complete
Nothing is left behind with Super Grate. Files, Media, Contacts, Emails, Windows Settings, Program Data & Internet Settings are all accounted for.
```
I have to say, that it will leave most settings behind unfortunately.

**Comment by krisdb2009** [comment] 2021-06-08 16:12
Again this is a USMT limitation, some things, by design are not able to be copied. New MS Edge and Google Chrome's app data settings are encrypted and need to have a user login to unlock for example.

I would also disagree that the statement is not misleading, also it is not an advertisement as this software is free and open source.

Super Grate copies all the things listed on the landing page.

**Comment by edmundlaugasson** [comment] 2021-06-08 16:43
You mentioned before, that USMT can copy lot of stuff. Still there is no option to configure it so, that it would copy all files under user profile? I guess it would just update those parameters appropriately and it would do the trick, if at all.

**Comment by krisdb2009** [comment] 2021-06-08 17:22
USMT and Windows does not work like this. You can't copy a profile over and expect everything to work. There are many GUIDs and profile specific SID information stored in the registry and filesystem that won't match up in the new profile. That is why USMT exists.

**Comment by edmundlaugasson** [comment] 2021-06-08 19:54
Sorry, but I don't get your statement, why USMT exist. I expect it to work and copy all these, you mentioned.
Still I don't agree the "Complete" statement at https://belowaverage.org/software/supersuite/supergrate/ - there is mentioned also emails, program data and internet settings - all these were left behind, when I used the program. I opened Thunderbird - it was empty, so was the Google Chrome. Now you can say (probably) - these are not Microsoft programs.
Still looking real solution, sounds like MS Windows is incomplete system, that is missing such an option....

**Comment by krisdb2009** [comment] 2022-10-29 12:59
After further research I see now that there may be a possibility of copying chrome data.
I am going to tinker with the default USMT settings that comes with Super Grate to see if I can get this to work.

**Comment by krisdb2009** [comment] 2022-10-31 03:29
I was able to get this to work in release https://github.com/belowaverage-org/SuperGrate/tree/1.3.5.0

**Closed by krisdb2009** 2022-10-31 03:29 UTC
Labels: enhancement
